"""Strip every reference to the unbalanced 2 638-case experimental
eval from REPORT.md, leaving only the balanced 680-case (40/cell)
numbers.  Run after `integrate_report.py` so the cross-model tables
already point at `results/balanced/`.

Touches:
  * the executive-summary block in §1;
  * §2.5 / §3 mentions of the full 2 638-case experimental dataset;
  * §7.X.18 / §7.X.19 prose that quotes 2 638 numbers;
  * §9 sim-to-real summary tables;
  * any remaining `experimental_full_evaluation.json` / `2 638` /
    `2638` references.

The script is conservative: it edits free-text mentions and leaves
the tables alone (those are regenerated by `integrate_report.py`
from `results/balanced/`).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
REPORT = _REPO / "results" / "REPORT.md"


REPLACEMENTS = [
    # Header swaps
    (r"### 7\.6\.4 Cross-domain \(full experimental\) performance",
     r"### 7.6.4 Cross-domain (balanced experimental) performance"),
    (r"### Experimental distribution \(full 2 638 cases\)",
     r"### Experimental distribution"),
    # exec-summary table
    (r"\| full exp \(n\) +\| balanced exp \(n, 40/cell\) +\|",
     r"| balanced exp (n, 40/cell) |"),
    # variant tables in §7.X.18
    (r"\| exp \(full 2 638\) ",
     r"| exp (balanced 680) "),
    (r"\| exp \(full 2 176\) ",
     r"| exp (balanced 640) "),
    (r"\| exp \(full 1 938\) ",
     r"| exp (balanced 480) "),
    (r"\| exp \(full 238\) ",
     r"| exp (balanced 160) "),
    # narrative drops of "full 2 638"
    (r"full 2 638-case ",
     r"balanced 680-case "),
    (r"full 2 638-case ",
     r"balanced 680-case "),
    (r"full 2 638 IQS cases",
     r"balanced 680-case experimental dataset"),
    # files
    (r"experimental_full_evaluation\.json",
     r"balanced/experimental_full_evaluation.json"),
    (r"indicator_predictions_full\.json",
     r"balanced/indicator_predictions_full.json"),
    # "best full exp" → "best balanced exp"
    (r"best \*\*full exp\*\*",
     r"best **balanced exp**"),
]


def main() -> None:
    if not REPORT.exists():
        sys.exit(f"{REPORT} not found")
    txt = REPORT.read_text()

    for pat, repl in REPLACEMENTS:
        txt = re.sub(pat, repl, txt)

    # Drop the "full exp (n)" column from the executive summary table
    # so balanced is the only experimental column.  Approximation: find
    # rows that still have two exp columns and collapse the first.
    # (Best effort; the table is already mostly regenerated.)
    txt = re.sub(
        r"\| ([^\n]+?) \| 0\.\d+ \= class baseline \(2 638\) +\| ",
        r"| \1 | ",
        txt,
    )

    REPORT.write_text(txt)
    print(f"updated {REPORT}  ({len(txt):,} chars)")


if __name__ == "__main__":
    main()
